### ISSUE TITLE
replace-css-classes Bootstrap 4 kompatibel

### ISSUE THREAD

**Issue by bschi** [contao-bootstrap/templates#11]
Ich verwende Bootstrap 4 und möchte gerne bspw. die pull-right Klasse, die durch replace-css-classes ersetzt wird, überschreiben, da diese nicht mehr kompatibel zu Bootstrap 4 ist. Wie kann ich das am besten machen? Die Konfiguration kann ich im Backend leider nicht anpassen, da es keine entsprechenden Optionen dafür gibt.

**Comment by dmolineus** [comment]
Grundsätzlich unterstützt die Erweiterung (noch) nicht Bootstrap 4. Daher biete ich hierfür auch keinen Support.  An sich lässt sich die Konfiguration aber über ein eigenes Modul überschreiben, analog dazu wie die Bootstrap Komponenten eine contao-bootstrap.php mitbringen.

**Comment by dmolineus** [comment]
Bei Supportfragen mit das Contao-Forum nutzen. https://community.contao.org/de/forumdisplay.php?169-contao-bootstrap
