### ISSUE TITLE
Pagination: current status: add active

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/templates#15]
add css class active to use the BS highlight

https://github.com/contao-bootstrap/templates/blob/d9b05e32bbd3609af56cc682a7429fdddddd0f26/module/templates/3.4/pagination_34.html5#L15

```diff
- <li><span class="current"><?php echo $page['page']; ?></span></li>
+ <li class="active"><span class="current"><?php echo $page['page']; ?></span></li>
```

**Comment by dmolineus** [comment]
Added with 555e4ab.

**Comment by zonky2** [comment]
thx
