### ISSUE TITLE
add "transfer" classes "btn" in ce_hyperlink to a-tag

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/templates#22]
With the CE Hyperlink it would be great if the classes "btn" and "btn-*" as well as "d-block" are passed on to the a-Tag like with "img-*" and don't end up in the DIV...

so that it looks like this then :
Input: `col-md-6 btn btn-primary d-block`
to
```
<div class="ce_hyperlink col-md-6 last block">  
    <a class="btn btn-primary d-block" href="address list.html" class="hyperlink_txt" title="address list" rel="">address list</a>
</div>
```

**Comment by dmolineus** [comment]
Features is added with b3ba33b.
