### ISSUE TITLE
gallery_bs_carousel Template aus contao-bootstrap/templates 2.2.0 funktioniert nicht mit Bootstrap 4

### ISSUE THREAD

**Issue by Alexander060101** [contao-bootstrap/templates#27]
Hallo,

ich habe ein Galerie-Element mit "gallery_bs_carousel" Galerie-Template zu meinem Artikel hinzugefügt und mich gewundert, wieso nur die Pfeile, nicht aber die .carousel-items angezeigt werden.

Es stellte sich heraus, dass die .active Klasse bei einem der .carousel-items initial gesetzt werden muss.
Aus der Bootstrap Doku https://getbootstrap.com/docs/4.4/components/carousel:
"The .active class needs to be added to one of the slides otherwise the carousel will not be visible."

Das ist auch bereits seit Bootstrap 4.0 so, weshalb es mich wundert, dass das noch nicht aufgefallen ist.
Oder mache ich etwas falsch?

Besten Dank schon mal.

Gruß
Alexander

**Comment by Alexander060101** [comment]
Habe diese kleine Änderung bei mir vorgenommen, nun funktioniert es.

![grafik](https://user-images.githubusercontent.com/12053064/137625835-a799c593-611b-4b0d-b191-eb4153a18e46.png)

**Comment by dmolineus** [comment]
Fixed in 2.3.1.
