### ISSUE TITLE
Newslist

### ISSUE THREAD

**Issue by squareZ** [contao-bootstrap/templates#3]
Hi everyone!

When I create a newslist and display it on my website, it adds **col-lg-6** automatically as class to it. But I didn't even assign any classes yet. Is there a way to avoid this?

I'm using Contao 3.4.2 with the bundle package. The template I've choosen for the newslist is _news_latest_.

```html
[...]
<div class="mod_newslist block">
	<div class="layout_latest arc_2 block first last even">
		<p class="info">
			<time datetime="2015-01-25T21:03:00+01:00">25.01.2015 21:03</time>
		</p>
		<h2><a href="news/hello-world.html" title="Den Artikel lesen: Hello World!">Hello World!</a></h2>
		<div class="teaser">
			<div class="col-lg-6 col_1 first"> <--- here
				<div class="ce_text block">
					<p>
						Magna aliquyam erat, sed diam voluptua. [...]
					</p>
				</div>
			</div>
		</div>
		<p class="more">
			<a href="news/hello-world.html" title="Den Artikel lesen: Hello World!">Weiterlesen … <span class="sr-only">Hello World!</span></a>
		</p>
	</div>
</div>
[...]
```

**Comment by dmolineus** [comment]
I actually do not provide any templates for the news module neighter set the `col` classes magically. So I'm wondering how your teaser is build.

Where does the content in the `teaser` div comes from? Do you use an insert tag? How does the HTML in your teaser element looks like?

Neighter Contao nor Contao-Bootstrap render following structure:

```php
<div class="col-lg-6 col_1 first"> 
    <div class="ce_text block">
    </div>
</div>
```

**Comment by squareZ** [comment]
Well, I should not handle with stuff like this when it's too late. Because this morning, after checking the sourcecode I found out, that I had a jquery part form my old theme in it that has added the classes to the div. Big fail! :confounded:

Anyways, thanks for the pointer!
