### ISSUE TITLE
Warning: Undefined array key "subitems"

### ISSUE THREAD

**Issue by srhinow** [contao-bootstrap/templates#30]
unter 
PHP 8.2
Contao 4.13

kommt dieser Fehler da das Vorhandensein von subitems in der https://github.com/contao-bootstrap/templates/blob/613ade363a4d980cecebdffbfdd8d4281269aaa3/src/View/Nav/NavItemHelper.php#L22 nicht mit isset() abgefragt wird.

Das gleiche dann im Template https://github.com/contao-bootstrap/templates/blob/613ade363a4d980cecebdffbfdd8d4281269aaa3/src/Resources/contao/templates/nav/nav_bs.html5#L13

**Comment by dmolineus** [comment]
Fixed in 2.3.1.
