### ISSUE TITLE
Menu of news archive

### ISSUE THREAD

**Issue by ghost** [contao-bootstrap/templates#4]
Hi,

I hope this section is right.

Could you provide a special bootstrap template for the menu of the news archive?

**Comment by dmolineus** [comment]
Yes, it belongs to the templates package.

Not sure if I support a template for that because the usage could be different how to display the news archive. Do you have any suggestions which Bootstrap component could be used for?

**Comment by squareZ** [comment]
Well, I've played a little bit around with it but end up with this blog post here: http://wpeden.com/tipsntuts/twitter-bootstrap-dropdown-on-hover-and-activating-click-event-on-parent-item/ Looks good so far, but requires additional CSS and extra classes as I think that this behaviour may be destructive for other navigations.

**Comment by dmolineus** [comment]
Think it's better a custom template adjustment in the project where it's required.
