### ISSUE TITLE
Templates deaktiviert Image-Polyfill

### ISSUE THREAD

**Issue by kein-nickname** [contao-bootstrap/templates#7]
Wenn das Bootstrap-Templates Modul aktiviert ist, funktioniert Image-Polyfill nicht mehr. Nach Deaktivierung in den Einstellung geht dies wieder!

**Comment by dmolineus** [comment]
As a workaround create a `picture_default` template using the backend template editor and copy the original template from https://github.com/contao/core/blob/master/system/modules/core/templates/picture/picture_default.html5 into it.

**Comment by dmolineus** [comment]
Fixed in 04cb3312c5f666c9b21ae00eaaab4b9b4590c451.
