### ISSUE TITLE
Support table- class replacing for Contao 3.4+

### ISSUE THREAD

**Issue by rflx** [contao-bootstrap/templates#9]
Hi,
would it be possible to implement a class replacement for the content element table (.ce_table) like the img- class replacement does? I mean to switch the base class `table` from .ce_text to its child element `<table>`. It would also be great to add support for the other classes like `table-striped`, `table-bordered`, `table-hover` and `table-condensed`. http://getbootstrap.com/css/#tables

`<table class="table table-striped">
  ...
</table>`

Cheers
rflx

**Comment by dmolineus** [comment]
It's already implemented but limited to the ce_table* templates. Does it work there? Or where do you want to use it?

https://github.com/contao-bootstrap/templates/blob/master/module/config/contao-bootstrap.php#L21-L25

**Comment by rflx** [comment]
Oh crap! I've only tried with the `table` class. It does the magic when you enter `table-condensed`, but when i'm only entering `table` there will be no replacement. Is that right?

Thx and cheers

**Comment by dmolineus** [comment]
Oh I see. The single `table` class is not set. I quite often use `table-striped` so I didn't reliaze it. Gonna fix it.

**Comment by dmolineus** [comment]
Got fixed in release 1.0.1, see edd169596a8bf784d5b9dc3a16ceac4e199b8954.
